In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) #Tạo ma trận x kích thước 4 hàng × 3 cột.

In [3]:
v = np.array([1, 0, 1]) #Tạo vector v gồm 3 phần tử

In [4]:
y = np.empty_like(x) #Tạo mảng y có cùng kích thước và dtype với x, nhưng giá trị ban đầu là rác

In [5]:
for i in range(4):
    y[i, :] = x[i, :] + v #Lấy hàng thứ i của x, cộng từng phần tử với v, rồi gán kết quả vào hàng thứ i của y

In [6]:
print(y) #In kết quả của y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
