In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) #Tạo ma trận x kích thước 4×3

In [3]:
v = np.array([1, 0, 1]) #Tạo vector v gồm 3 phần tử

In [4]:
y = x + v #cộng từng phần tử của x với v

In [5]:
print(y) #In kết quả của y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
