In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3]) #v có 3 phần tử (shape = (3,))

In [3]:
w = np.array([4,5]) #w có 2 phần tử (shape = (2,))

In [4]:
print(np.reshape(v, (3, 1)) * w) #biến v thành vector cột và nhân với w

[[ 4  5]
 [ 8 10]
 [12 15]]


In [5]:
x = np.array([[1,2,3], [4,5,6]]) #Tạo ma trận 2x3

In [6]:
print(x + v) #cộng từng hàng của x với v

[[2 4 6]
 [5 7 9]]


In [7]:
print((x.T + w).T) #Cộng x.T với w. Sau đó .T lần nữa để trở lại shape ban đầu 2×3

[[ 5  6  7]
 [ 9 10 11]]


In [8]:
print(x + np.reshape(w, (2, 1))) #biến w thành vector cột 2×1, cộng từng cột của x với các giá trị 4 và 5

[[ 5  6  7]
 [ 9 10 11]]
