In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3]) #Tạo vector v có 3 phần tử.

In [3]:
w = np.array([4,5]) #Tạo vector w có 2 phần tử

In [4]:
print(np.reshape(v, (3, 1)) * w) #biến v thành vector cột 3×1 rồi nhân với w

[[ 4  5]
 [ 8 10]
 [12 15]]


In [5]:
x = np.array([[1,2,3], [4,5,6]]) #Ma trận x kích thước 2×3

In [6]:
print(x + v) #cộng từng hàng của x với v

[[2 4 6]
 [5 7 9]]


In [7]:
print((x.T + w).T) #x.T là ma trận 3×2. Cộng vector w (2 phần tử) theo cột của x.T, .T lại để quay về kích thước 2×3.

[[ 5  6  7]
 [ 9 10 11]]


In [8]:
print(x + np.reshape(w, (2, 1))) #biến w thành vector cột 2×1

[[ 5  6  7]
 [ 9 10 11]]


In [9]:
print(x * 2) #Nhân từng phần tử của x với 2

[[ 2  4  6]
 [ 8 10 12]]
