In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) #Tạo mảng có kích thước 4x3

In [3]:
print(a) #In ra mảng a

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
b = np.array([0, 2, 0, 1]) #Mảng b chứa các chỉ số cột sẽ được lấy cho từng hàng

In [5]:
print(a[np.arange(4), b]) #Truy cập theo từng cặp chỉ số (hàng, cột)

[ 1  6  7 11]


In [6]:
a[np.arange(4), b] += 10 #Cộng thêm 10 vào các phần tử vừa chọn

In [7]:
print(a) #in ra mảng a

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
