In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]], dtype=np.float64) #Tạo ma trận 2×2 kiểu float64

In [3]:
y = np.array([[5,6],[7,8]], dtype=np.float64) #Tạo ma trận 2×2 kiểu float64

In [4]:
print(x + y) #Cộng từng phần tử của hai ma trận.

[[ 6.  8.]
 [10. 12.]]


In [5]:
print(np.add(x, y)) #Cộng từng phần tử của hai ma trận.

[[ 6.  8.]
 [10. 12.]]


In [6]:
print(x - y) #Trừ từng phần tử

[[-4. -4.]
 [-4. -4.]]


In [7]:
print(np.subtract(x, y)) #Trừ từng phần tử

[[-4. -4.]
 [-4. -4.]]


In [8]:
print(x * y) #Nhân từng phần tử

[[ 5. 12.]
 [21. 32.]]


In [9]:
print(np.multiply(x, y)) #Nhân từng phần tử

[[ 5. 12.]
 [21. 32.]]


In [10]:
print(x / y) #Chia từng phần tử.

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [11]:
print(np.divide(x, y)) #Chia từng phần tử

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
print(np.sqrt(x)) #Lấy căn bậc hai từng phần tử trong x.

[[1.         1.41421356]
 [1.73205081 2.        ]]
